changes
mate-academy/qa_cypress_e2e_student_registration_form pull request #265
Opened 2023-07-17 15:36 UTC by 7Lena7555

2023-07-17 16:48 UTC, bkovalchukk commented
gj

2023-07-18 06:55 UTC, NataliiaSolotva requested changes
Changes are required. Check the comments, please

2023-07-18 06:55 UTC, NataliiaSolotva commented on cypress/e2e/registration.cy.js
> +  let user;
Empty line is required)

2023-07-18 06:55 UTC, NataliiaSolotva commented on cypress/e2e/registration.cy.js
>    it('', () => {
Remove this row, please.
You have it block inside it block.

2023-07-18 06:55 UTC, NataliiaSolotva commented on cypress/e2e/registration.cy.js
> +        .should('contain', '02 Dec ,2009');
This check fails. Fix it, please

2023-07-18 06:55 UTC, NataliiaSolotva commented on cypress/e2e/registration.cy.js
> +        .should('contain', user.streetAddress);
This check fails. Fix it, please

2023-07-18 09:18 UTC, NataliiaSolotva requested changes
Some changes are required

2023-07-18 15:22 UTC, vlasiuksasha approved these changes
GJ!

2025-06-13 11:05 UTC, closed without merging