Add tests for 'Registration.cy.js'
mate-academy/qa_cypress_e2e_student_registration_form pull request #344
Opened 2023-12-05 19:27 UTC by LosKamilos91

2023-12-06 11:52 UTC, Bondi13 requested changes
Please read the comments and make adjustments.

2023-12-06 11:52 UTC, Bondi13 commented on cypress/e2e/registration.cy.js
> +    cy.get('#city > .css-yk16xz-control > .css-1hwfws3').type('Delhi{enter}');
Please construct getters according to the checklist provided in the task. Do not use spaces or `>` etc.

2023-12-06 11:52 UTC, Bondi13 commented on cypress/e2e/registration.cy.js
> +
Assert if the form was submitted successfully.

2023-12-06 11:52 UTC, Bondi13 commented on cypress/e2e/registration.cy.js
> +    cy.get('form').get('input[placeholder="First Name"]').type('testName');
Please use randomly generated data each time. Create a generator in a separate file (e.g. support or config).

2023-12-11 18:06 UTC, anna-lymorenko approved these changes
Great job!

2025-08-31 18:28 UTC, closed without merging